# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestloan',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
